### ISSUE TITLE
Provide an option to collect metrics from all tubes

### ISSUE THREAD

**Issue by dannyk81** [davidtannock/beanstalkd_exporter#1]
Hey @davidtannock!

Great job on this exporter, we were testing it out and overall really pleased.

Our only issue is that it currently requires that we provide a list of tubes to collect metrics for which is a bit tricky for us, since we have many different deployments with different tubes being used and in general we want to collect metrics for all of them.

Would you consider an option to collect stats from all tubes?

**Comment by davidtannock** [comment]
Hi @dannyk81 

Thanks for the feedback.

Yes, that sounds like a useful option. I'll have another branch soon.

**Comment by davidtannock** [comment]
Hi @dannyk81 

Branch [alltubes](https://github.com/davidtannock/beanstalkd_exporter/tree/alltubes) adds a new option, `--beanstalkd.allTubes`, for fetching metrics for all tubes. I've updated the readme.

Can you let me know how well that works?

Thanks.

**Comment by dannyk81** [comment]
Thanks @davidtannock!

We're going to test it out and update.

**Comment by dannyk81** [comment]
Hey @davidtannock, we've deployed this on a couple of nodes and so far seem to work as advertised 👍 

Another team needs to validate this, so we may have more feedback later, but overall the `allTubes` flag seem to work really well.

Thanks again for the prompt response on this.

**Comment by davidtannock** [comment]
Thanks @dannyk81 for testing it out.

I'll close the issue for now.
